{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Dumb calculator"
   ]
  },
  {
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "# \"\"\"\n",
    "This is a dumb calculator that can add and subtract whole numbers from zero to five.\n",
    "When you run the code, you are prompted to enter two numbers (in the form of English\n",
    "word instead of number) and the operator sign (also in the form of English word).\n",
    "The code will perform the calculation and give the result if your input is what it\n",
    "expects.\n",
    "\n",
    "The code is very long and messy. Refactor it according to what you have learned about\n",
    "code simplicity and efficiency.\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# First step, introduce a function that could be called\n",
    "# The function \"calculator\" has three inputs, a, b and c\n",
    "\n",
    "\n",
    "# Start of function\n",
    "\n",
    "def calculator(a,b,c):\n",
    "    \n",
    "    if a == 'zero' and b == 'plus'  and c == 'zero':\n",
    "        print(\"zero plus zero equals zero\")\n",
    "    if a == 'zero' and b == 'plus'  and c == 'one':\n",
    "        print(\"zero plus one equals one\")\n",
    "    if a == 'zero' and b == 'plus'  and c == 'two':\n",
    "        print(\"zero plus two equals two\")\n",
    "    if a == 'zero' and b == 'plus'  and c == 'three':\n",
    "        print(\"zero plus three equals three\")\n",
    "    if a == 'zero' and b == 'plus'  and c == 'four':\n",
    "        print(\"zero plus four equals four\")\n",
    "    if a == 'zero' and b == 'plus'  and c == 'five':\n",
    "        print(\"zero plus five equals five\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'zero':\n",
    "        print(\"one plus zero equals one\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'one':\n",
    "        print(\"one plus one equals two\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'two':\n",
    "        print(\"one plus two equals three\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'three':\n",
    "        print(\"one plus three equals four\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'four':\n",
    "        print(\"one plus four equals five\")\n",
    "    if a == 'one' and b == 'plus'  and c == 'five':\n",
    "        print(\"one plus five equals six\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'zero':\n",
    "        print(\"two plus zero equals two\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'one':\n",
    "        print(\"two plus one equals three\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'two':\n",
    "        print(\"two plus two equals four\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'three':\n",
    "        print(\"two plus three equals five\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'four':\n",
    "        print(\"two plus four equals six\")\n",
    "    if a == 'two' and b == 'plus'  and c == 'five':\n",
    "        print(\"two plus five equals seven\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'zero':\n",
    "        print(\"three plus zero equals three\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'one':\n",
    "        print(\"three plus one equals four\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'two':\n",
    "        print(\"three plus two equals five\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'three':\n",
    "        print(\"three plus three equals six\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'four':\n",
    "        print(\"three plus four equals seven\")\n",
    "    if a == 'three' and b == 'plus'  and c == 'five':\n",
    "        print(\"three plus five equals eight\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'zero':\n",
    "        print(\"four plus zero equals four\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'one':\n",
    "        print(\"four plus one equals five\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'two':\n",
    "        print(\"four plus two equals six\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'three':\n",
    "        print(\"four plus three equals seven\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'four':\n",
    "        print(\"four plus four equals eight\")\n",
    "    if a == 'four' and b == 'plus'  and c == 'five':\n",
    "        print(\"four plus five equals nine\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'zero':\n",
    "        print(\"five plus zero equals five\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'one':\n",
    "        print(\"five plus one equals six\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'two':\n",
    "        print(\"five plus two equals seven\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'three':\n",
    "        print(\"five plus three equals eight\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'four':\n",
    "        print(\"five plus four equals nine\")\n",
    "    if a == 'five' and b == 'plus'  and c == 'five':\n",
    "        print(\"five plus five equals ten\")\n",
    "\n",
    "\n",
    "    if a == 'zero' and b == 'minus' and c == 'zero':\n",
    "        print(\"zero minus zero equals zero\")\n",
    "    if a == 'zero' and b == 'minus' and c == 'one':\n",
    "        print(\"zero minus one equals negative one\")\n",
    "    if a == 'zero' and b == 'minus' and c == 'two':\n",
    "        print(\"zero minus two equals negative two\")\n",
    "    if a == 'zero' and b == 'minus' and c == 'three':\n",
    "        print(\"zero minus three equals negative three\")\n",
    "    if a == 'zero' and b == 'minus' and c == 'four':\n",
    "        print(\"zero minus four equals negative four\")\n",
    "    if a == 'zero' and b == 'minus' and c == 'five':\n",
    "        print(\"zero minus five equals negative five\")\n",
    "    if a == 'one' and b == 'minus' and c == 'zero':\n",
    "        print(\"one minus zero equals one\")\n",
    "    if a == 'one' and b == 'minus' and c == 'one':\n",
    "        print(\"one minus one equals zero\")\n",
    "    if a == 'one' and b == 'minus' and c == 'two':\n",
    "        print(\"one minus two equals negative one\")\n",
    "    if a == 'one' and b == 'minus' and c == 'three':\n",
    "        print(\"one minus three equals negative three\")\n",
    "    if a == 'one' and b == 'minus' and c == 'four':\n",
    "        print(\"one minus four equals negative three\")\n",
    "    if a == 'one' and b == 'minus' and c == 'five':\n",
    "        print(\"one minus five equals negative four\")\n",
    "    if a == 'two' and b == 'minus' and c == 'zero':\n",
    "        print(\"two minus zero equals two\")\n",
    "    if a == 'two' and b == 'minus' and c == 'one':\n",
    "        print(\"two minus one equals one\")\n",
    "    if a == 'two' and b == 'minus' and c == 'two':\n",
    "        print(\"two minus two equals zero\")\n",
    "    if a == 'two' and b == 'minus' and c == 'three':\n",
    "        print(\"two minus three equals negative one\")\n",
    "    if a == 'two' and b == 'minus' and c == 'four':\n",
    "        print(\"two minus four equals negative two\")\n",
    "    if a == 'two' and b == 'minus' and c == 'five':\n",
    "        print(\"two minus five equals negative three\")\n",
    "    if a == 'three' and b == 'minus' and c == 'zero':\n",
    "        print(\"three minus zero equals three\")\n",
    "    if a == 'three' and b == 'minus' and c == 'one':\n",
    "        print(\"three minus one equals two\")\n",
    "    if a == 'three' and b == 'minus' and c == 'two':\n",
    "        print(\"three minus two equals one\")\n",
    "    if a == 'three' and b == 'minus' and c == 'three':\n",
    "        print(\"three minus three equals zero\")\n",
    "    if a == 'three' and b == 'minus' and c == 'four':\n",
    "        print(\"three minus four equals negative one\")\n",
    "    if a == 'three' and b == 'minus' and c == 'five':\n",
    "        print(\"three minus five equals negative two\")\n",
    "    if a == 'four' and b == 'minus' and c == 'zero':\n",
    "        print(\"four minus zero equals four\")\n",
    "    if a == 'four' and b == 'minus' and c == 'one':\n",
    "        print(\"four minus one equals three\")\n",
    "    if a == 'four' and b == 'minus' and c == 'two':\n",
    "        print(\"four minus two equals two\")\n",
    "    if a == 'four' and b == 'minus' and c == 'three':\n",
    "        print(\"four minus three equals one\")\n",
    "    if a == 'four' and b == 'minus' and c == 'four':\n",
    "        print(\"four minus four equals zero\")\n",
    "    if a == 'four' and b == 'minus' and c == 'five':\n",
    "        print(\"four minus five equals negative one\")\n",
    "    if a == 'five' and b == 'minus' and c == 'zero':\n",
    "        print(\"five minus zero equals five\")\n",
    "    if a == 'five' and b == 'minus' and c == 'one':\n",
    "        print(\"five minus one equals four\")\n",
    "    if a == 'five' and b == 'minus' and c == 'two':\n",
    "        print(\"five minus two equals three\")\n",
    "    if a == 'five' and b == 'minus' and c == 'three':\n",
    "        print(\"five minus three equals two\")\n",
    "    if a == 'five' and b == 'minus' and c == 'four':\n",
    "        print(\"five minus four equals one\")\n",
    "    if a == 'five' and b == 'minus' and c == 'five':\n",
    "        print(\"five minus five equals zero\")\n",
    "\n",
    "        \n",
    "# Changed the \"wrong input\" part for a while loop shown in the last code line \n",
    "\n",
    "    print(\"Thanks for using this calculator, goodbye :)\")\n",
    "\n",
    "    \n",
    "# End of function"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Introduce a list with all possiblities (0ne-five), short list\n",
    "# This list can be used in the while loop, used in the next line\n",
    "\n",
    "lst= ['zero','one','two','three','four','five']\n",
    "lst2= ['minus','plus']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Introduce a while loop, otherwise a \"wrong\" input is only corrected at the end\n",
    "\n",
    "# Start of calculator\n",
    "print('Welcome to this calculator!')\n",
    "print('It can add and subtract whole numbers from zero to five')\n",
    "\n",
    "# If not 0-5 ask again!\n",
    "a = input('Please choose your first number (zero to five): ')\n",
    "while a not in lst:\n",
    "    print(\"Wrong input!\")\n",
    "    a = input('Please choose your first number again (zero to five): ')\n",
    "\n",
    "# If not plus or minus, ask again!\n",
    "b = input('What do you want to do? plus or minus: ')\n",
    "while b not in lst2:\n",
    "    print(\"Wrong input!\")\n",
    "    b = input('What do you want to do? plus or minus: ')\n",
    "\n",
    "# If not 0-5 ask again!\n",
    "c = input('Please choose your second number (zero to five): ')\n",
    "while c not in lst:\n",
    "    print(\"Wrong input!\")\n",
    "    c = input('Please choose your second number again (zero to five): ')\n",
    "    \n",
    "# If all inputs (a,b,c) are correct calculate difference with calling calculator function    \n",
    "calculator(a,b,c)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
